### ISSUE TITLE
[User Service] Handle error response for duplicate usernames for sign ups

### ISSUE THREAD

**Issue by izzahaj** [CS3219-AY2324S1/ay2324s1-course-assessment-g34#46]
## Description:
To be udpated

## Steps to Reproduce:
To be updated

### Expected Behavior:
To be updated

### Actual Behavior:
To be updated

### Additional Information:
N/A

**Comment by wweqg** [comment]
Currently, the user service is returning 400 Bad requests on duplicate usernames
